# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4fd23c5ff0edd56b468e7db39c3779c5d14fbf2eddd6408817b696bf8c07d8eddcc1bf57b693410f871922133d5375c25a5f147ff6f1811822feed708e86053

test:
  secret_key_base: ab2f2cbd3d8d0221073681a86fb863316348763ee14b6d71428f5999ff7a199b524a7859d10f16059d1fb6df01274e1348df72b08e84d9ed5049c541df0eb959

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
